### PR TITLE
New port for SDL2

### PR DESCRIPTION
**Pull request by rgson**
I've created a new port for SDL2, following the discussion in issue #19.

The new port is heavily based on the existing SDL1 port with Laura Michaels' SDL2 patch applied, but with a fair amount of important fixes and additional changes on top.

Firstly, the SDL2 port is updated to work with the current version of PDCurses. On the branch targeted by this pull request (`fork/Bill-Gray`), "the current version" means this fork's `master` branch at the time of writing (commit 497c619). It also includes fork-specific changes to match those made to the SDL1 port.

Secondly, I have fixed various issues that remained after applying the SDL2 patch. Rendering, resizing and mouse wheel support was broken. Some SDL1 code also remained, making compilation fail whenever `WIDE=Y` was not used.

Thirdly, I fixed the broken text input and also introduced proper wide character input for `PDC_WIDE` builds. Even "regular" input was broken due to differences between SDL1 and 2, allowing only characters with dedicated keys on the US keyboard layout and upper-case letters to be entered, but no special characters (e.g. Shift-2 would produce 2, not @). Now input should work as expected and respect the current keyboard layout, too. Unicode input is also supported when compiled with `WIDE=Y`.

The decision to make SDL2 a stand-alone port was taken both to avoid an unmaintainable mess of nested `#ifdef`s (the versions differ in `PDC_WIDE` sections, too) and to comply with the "PDCurses Implementor's Guide" (thus leaving the possibility of having it pulled into the upstream repository open).

Let me know if anything needs changing or if you find any remaining issues that I have missed.

### CODE REVIEW

**Comment by Bill-Gray** [comment]
Hi Robin,

    Thank you!  I took a quick look at this last night,  and everything seemed
to work quite nicely with both WIDE=Y and "non-wide" builds.

    There are,  as you doubtless saw,  issues when building against the Win32a
fork of PDCurses.  'testcurs' fails with an undefined reference to
PDC_set_function_key.  Overlined,  strikeout,  and dimmed attributes,  RGB
colors,  user resizing,  added ACSes,  etc. don't work.  But I agree that
providing something that can get merged into the upstream PDCurses is an
excellent start.  (And even if William McBrine never pulls your changes,
your patch _can_ be used by anyone who is interested.)

    Unless you've a better idea,  I expect I'll pull it into Bill-Gray/PDCurses
"as is".  Then we can think about changes.  Does that sound reasonable to you?

-- Bill

**Comment by rgson** [comment]
Did you try the version on the `fork/Bill-Gray` branch? On that branch I've updated the port for the current version of this repository rather than the current version of wmcbrine/PDCurses, and I've included the fork-specific changes that you have made to SDL1 in the SDL2 port.

It's possible that I've missed some of the fork-specific features you mentioned, though I believe at least some of them should be working. It should at the very least build properly. The `PDC_set_function_key` function is implemented the same as for SDL1 on that branch, too: https://github.com/rgson/PDCurses-SDL2/blob/fork/Bill-Gray/sdl2/pdcscrn.c#L401.

If you're experiencing these problems with the `fork/Bill-Gray` branch, then I think we better wait with merging this pull request until it builds properly. Some missing features might be OK, but there's little point in introducing a completely unusable port, in my opinion.

**Comment by Bill-Gray** [comment]
On 2016-11-22 13:49, Robin Gustafsson wrote:
> Did you try the version on the |fork/Bill-Gray| branch?

    [Groan]  Nevermind;  that was the problem.  That branch works Just
Fine,  and implements most of the fork-specific changes.

    Now that I'm looking in the right place,  I think we're good to go.

> It's possible that I've missed some of the fork-specific features you
> mentioned, though I believe at least some of them should be working.

    Just about all of them.  I see what you mean about manual resizing not
working (looks as if we get an endless stream of KEY_RESIZE messages...
I'll investigate;  it may not be a big deal to fix it.  And there are
various features that didn't get into SDL1,  such as RGB text.  But all
that should be relatively easy;  you've done the hard part.)

-- Bill

**Comment by GitMensch** [comment]
@rgson I've tested this against SDL2.0.6 and (at least with MINGW64) many "recent" features are missing:

grafik

compared to the win32 variant:

win32a

Is this expected? Can you add (some) of the missing features?

**Comment by GitMensch** [comment]
Note: When compiling with WIDE=Y (which uses SDL2_ttf) all tests work but newtest, which always results in a segmentation fault. Running thru GDB didn't helped much:

~~~
Starting program: C:\PDCurses.git\sdl2/newtest.exe
[New Thread 10668.0x23d0]
[New Thread 10668.0x3384]
[New Thread 10668.0x212c]
[New Thread 10668.0x30d8]
[New Thread 10668.0x794]

Program received signal SIGSEGV, Segmentation fault.
0x757d0e2b in vswprintf () from C:\WINDOWS\SysWOW64\msvcrt.dll
~~~

Not sure but this may relate to #58.

**Comment by GitMensch** [comment]
Note: When compiling with WIDE=Y (which uses SDL2_ttf) all tests work but newtest, which always results in a segmentation fault.
The same happens with win32a in this environment therefore this is likely a problem in the demo, not in sdl2 port.

Running thru GDB didn't helped much:

~~~
Starting program: C:\PDCurses.git\sdl2/newtest.exe
[New Thread 10668.0x23d0]
[New Thread 10668.0x3384]
[New Thread 10668.0x212c]
[New Thread 10668.0x30d8]
[New Thread 10668.0x794]

Program received signal SIGSEGV, Segmentation fault.
0x757d0e2b in vswprintf () from C:\WINDOWS\SysWOW64\msvcrt.dll
~~~

Not sure but this may relate to #58.

**Comment by rgson** [comment]
@GitMensch Thanks for the comprehensive post.

I guess the port is not exactly expected to be missing features, but I'm not terribly surprised either as I never paid much attention to it. My focus was on creating a SDL2 counterpart of the SDL1 port, and so I never attempted to add features exceeding those of the SDL1 port. Do you know if the missing features are available in the SDL1 port?

I'm currently no longer working on this. My original use-case is no longer relevant and, thus, I'm currently not even using this port (nor any other) anymore. If I've missed some features from the SDL1 port then I'll try to reserve some time to port them over. If it's a matter of implementing the features from scratch then I fear I currently don't have the time to commit to doing it, since it'd fall entirely outside of my currently active projects.

**Comment by Bill-Gray** [comment]
@GitMensch, @rgson - some missing features involve colors,  and result from the fact that both SDL1 and SDL2 flavors of PDCurses use a 256-color palette.  The RGB text,  currently appearing in oddball colors,  could be corrected either by using a 24-bit image or by mapping RGB colors to their nearest counterpart within the 256-color palette,  which actually wouldn't be all that difficult to do.  (Though using 24-bit color would look better,  and I think both SDL1 and 2 provide ways of doing it.)

"Real blinking" is supported in X11 and Win32a by setting up timing events,  by default at half-second intervals.  That is to say,  every half second,  we invert all blinking text and switch the cursor state if that's blinking.  I don't know how,  or even if,  SDL1/2 handle timers.

Also in X11 and Win32a,  we can load 'normal',  bold,  italic,  and bold italic fonts,  and switch between the four of them as needed.  I think the same thing could be done in the SDL versions,  but at present,  it isn't.

User resizing fails in the SDL2 flavor.  I think Robin took a try at fixing this,  and so did I,  without success.  It may require greater knowledge of SDL2 to get it to work.

I've spent an hour or two investigating these issues,  but should say that I'm mostly using the X11 version,  and occasionally the Win32a version.  So these problems may await a more SDL-oriented person.

I do think that the fix I've just posted for issue #58 will probably allow you to to compile a WIDE=Y version of SDL2 newtest.

**Comment by GitMensch** [comment]
@Bill-Gray, @rgson 

Executing the wide variant works after 40b419a4f427ba60f07c84c036825a6803ded548:

SDL2, WIDE=Y, UTF8=Y

win32a 1, WIDE=Y, UTF8=Y
win32a 2, WIDE=Y, UTF8=Y

One additional thing that is missing are the different (new?) cursor modes, the only ones that are working are invisible and block (all others show as block).

Concerning resizing in SDL2 we may ask Laura Michaels - does anybody knows how to contact her?

@Bill-Gray 
>some missing features involve colors, and result from the fact that both SDL1 and SDL2 flavors of PDCurses use a 256-color palette. The RGB text, currently appearing in oddball colors, could be corrected either by using a 24-bit image or by mapping RGB colors to their nearest counterpart within the 256-color palette, which actually wouldn't be all that difficult to do. (Though using 24-bit color would look better, and I think both SDL1 and 2 provide ways of doing it.)

> "Real blinking" is supported in X11 and Win32a by setting up timing events, by default at half-second intervals. That is to say, every half second, we invert all blinking text and switch the cursor state if that's blinking. I don't know how, or even if, SDL1/2 handle timers.

> Also in X11 and Win32a, we can load 'normal', bold, italic, and bold italic fonts, and switch between the four of them as needed. I think the same thing could be done in the SDL versions, but at present, it isn't.

Can you try to fix these issues (and maybe the cursor modes)? In any case it would be good to create at least one issue with the "known" issues. We could split it later for all things that wont be solved easily.

**Comment by rgson** [comment]
@GitMensch I was in contact with Laura Michaels last year, back when I was working on this. I found her e-mail address on her website (http://www.distasis.com/connect.htm). It appears to be the same still.

**Comment by Bill-Gray** [comment]
@GitMensch , @rgson - Tricky bits (from my viewpoint) are 

(1) switching from a 256-color palette to either 16- or 24-bit full-color,  
(2) setting up some sort of timer to be triggered twice a second,
(3) handling user resizing events,
(4) adding italic,  bold,  and italic-bold fonts.

I don't plan on actually doing any of these.  However,  if (for example) (1) were done,  I could then set up RGB and dimmed text,  as well as "blinking" text that is actually "standout" text (the default).  Bold text could at least be implemented as brighter text,  the way it's done on OS/2,  DOS,  and Win32 console where we can't reset the fonts.  Once we were on full-color,  the rest of the work would not be especially difficult for me;  it would involve modest alteration of existing code in the X11 and Win32 flavors that already does the same thing.  But going to full-color is (I think) a Big Deal,  and not something I expect to tackle.

If (2) were done,  we could have "real" blinking text and a blinking cursor,  and I might take the modest effort required to make use of the assorted cursor styles implemented in win32a/pdcdisp.c in the 'redraw_cursor_from_index()' function.  I'd have expected that SDL provides some cross-platform way of saying "I want this function to be called at this interval",  and it probably does.  But my modest investigation did not find out how it's done.

I think Robin took a try at (3),  as did I,  but neither of us succeeded.

**Comment by rgson** [comment]
@Bill-Gray Correct; I tied to get (3) to work as part of my changes, but did not find the cause of the problem. I simply didn't have time to learn SDL2 well enough.

I think the best thing to do would be to open issues documenting the missing features. Hopefully, someone with more knowledge of SDL2 will be able to contribute fixes in the future.

**Comment by Bill-Gray** [comment]
Contradicting my statement that I didn't plan on doing much about SDL2... 324b7dbc3d98dde06851de691c667dbc533b6d72 adds full RGB,  dimmed text,  bold/bright shown highlit the way they are in X11 and Win32a.  I was able to do this because it turns out that SDL2 (and probably SDL1) are not really using a palette.  I thought we were limited to 256 colors in the SDL2 port,  without a major revision.  We weren't.

The issue with user-resizable windows turned out to be simpler than I thought;  see commit 4ffed48b242d9606b602bdb0d6e7a117e910c9a2 . In X11 and Win32a,  a KEY_RESIZE and full redraw only occurs when the window is stretched to the point where the number of columns or rows changes;  partial columns/rows are ignored.  We can't do that in SDL2.  As a result,  as the user resizes the window,  we'll be redrawing continuously.  Which is unfortunate,  but I think we're stuck with it.

I also see that SDL2 provides an SDL_AddTimer() function,  which should allow for a blinking cursor and "real" blinking text.  With those changes,  I think SDL2 would be almost a full sibling of the X11 and Win32a flavors,  though still lacking bold and italic and bold-italic fonts.

**Comment by GitMensch** [comment]
@Bill-Gray marvellous, I think it is really nice to have these features in SDL2, too. Please go on with the timer for SDL2 and *maybe* try afterwards if you can apply the same changes for SDL1.
In any case: if you fix mayor bugs or add new/missing features please try to always include an entry to the HISTORY file, otherwise we'll always have to check all commits before doing a release - and people that compile from master actually don't know what they get if they don't check all the commits since the last release.

... and I think after these changes are done we actually have enough to release 4.0.3 (or 4.1.0), maybe end of September? I'll wait with bragging about the 4.x release until then...

**Pull request merged**
