### PR TITLE
correct OW cross-compilation CMake scripts

### PR DESCRIPTION
**Pull request by jmalak**
overwrite CMake default values, they are only valid for Windows, not for cross-compilation
correct compiler driver name for 16-bit

### CODE REVIEW

**Comment by jmalak** [comment]
This should fix rest of problems related to Windows only support.
CMake need completely override configuration for cross-compilation

**Comment by jwinarske** [comment]
@GitMensch I tried this change in my branch and it's failing.  I'd like to understand these changes and properly test prior to merging into master.

```
-- The C compiler identification is OpenWatcom 2.0
System is unknown to cmake, create:
Platform/OS2 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Check for working C compiler: C:/Tools/watcom/binnt64/wcl386.exe
System is unknown to cmake, create:
Platform/OS2 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
-- Check for working C compiler: C:/Tools/watcom/binnt64/wcl386.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler
    "C:/Tools/watcom/binnt64/wcl386.exe"
  is not able to compile a simple test program.
  It fails with the following output:
```

**Comment by GitMensch** [comment]
Thank you @jwinarske, so we'll wait for @jmalak's explanation before the merge.
It is nice to have cross-compilation working again, but obviously it should still build on win32 :-)

**Comment by jwinarske** [comment]
Keep in mind Ubuntu distributes CMake 3.10, so that is the required baseline.

**Comment by jmalak** [comment]
I hope it could work with 3.10.

**Comment by jmalak** [comment]
You can not specify OS because CMake version < 3.17.2 support only Windows for OW.
For Cmake it looks like Windows, but real configuration is for different OS.

**Comment by jmalak** [comment]
I tested it with CMake 3.11.0 + OW 1.9 and it works on Windows for OS/2 32-bit and DOS 16/32-bit.

**Comment by jmalak** [comment]
I think it is resolved.
Main reason for problems was mismatch in used tools and used options and CMake used tool and option.
It is very confusing to mix wcl.. (default in CMake) with wcc.. tool.
It result in similar strange mistakes in dependency how it is configured.

Now wcl.. tool is used as default tool in CMake.

**Comment by GitMensch** [comment]
Thank you for the explanation. @jwinarske is everything resolved on your side, too?

**Comment by jmalak** [comment]
I added fix for proper file extensions for various file types
Most important is fix for executable file extensions.

**Comment by jmalak** [comment]
For your info, main ideas which I used for OW cross-compilation implementation by CMake without real CMake OW support (it is available for CMake version 3.17.2 and above) are as follow.

OW uses  "Generic" target (something as no-OS for target) hack for cross-compilation and override all existing CMake variables specific for Windows by new "language" specific variables.
"Generic" target ensure that existing (Windows specific) variables are ignored.
We cannot define any target platform specific variables because "Generic" target has minimal setup. I used hack with "language" specific variables which must be re-defined in cross-compilation for each specific target. These "language" specific variable is used as target specific that it works "transparent" way (not used by existing CMake OW Windows stuff).
Be careful because not all variable has appropriate "language" variable version and could be global.
Luckily no such variable exists now. I recommend to move to OW support in CMake as soon as possible to remove these hacks and get more reliable solution without any overriding of CMake variables. It is jiggery-pokery mainly for CMake backward compatibility (I tested it with CMake 3.10 on Ubuntu and on Windows). You have setup required Cmake version to 3.11. I don't know what is reason for this.
To use it with Ubuntu (Linux) is necessary to setup it to 3.10.

**Comment by jwinarske** [comment]
Do we have a clean set of appveyor logs somewhere with this change?

**Comment by jmalak** [comment]
I don't understand appveyor that I can not comment it.
It looks like you have not setup CI build on push requests, that is not checked in real environment.
Or I have some possibility to start CI bild for push request?
I did checks only localy with CMake installation on Windows 10 and Ubuntu.

**Comment by jwinarske** [comment]
If you have appveyor account you enable the project and it runs builds on all branch check-ins.

**Comment by jmalak** [comment]
OK I will create my account and try to run CI build on it.

**Comment by jmalak** [comment]
do you have some template/guide for appveyor setup?
It is possible somehow extend build for Ubuntu?

**Comment by jwinarske** [comment]
@jmalak See the .travis file.  Appveyor is only used for Windows builds, as it stores build artifacts.  Ideally the artifacts are published to the github repo.

**Comment by jwinarske** [comment]
@GitMensch This is good to merge.  I just validated changes via [Appveyor build](https://ci.appveyor.com/project/jwinarske/pdcurses-21dj3), and the Watcom jobs are all green.  Thanks!! @jmalak

**Comment by jmalak** [comment]
I will look on travis configuration and setup what is necessary to build it on Linux by Open Watcom.

**Comment by GitMensch** [comment]
Thanks for the work @jmalak and thanks for the review @jwinarske. I'd be excited to see building with ow in the travis build!

**Comment by jmalak** [comment]
I have test version of travis build with ow cross-compile build to DOS, DOS32 and OS/2 for OpenWatcom 1.9 and 2.0 on Linux. But Travis is little bit confusing by additional values for OW compilers that it needs some investigation.
OW 1.9 build is succesfull but OW 2.0 has a problem with wmake (64-bit) version (porting issue) that   I must fix OW 2.0 wake first.

**Pull request merged**
