### PR TITLE
cmake: mingw compatibility

### PR DESCRIPTION
**Pull request by sherpya**
- avoid settings /SUBSYSTEM:WINDOWS directly
- moved project directive: accidentally fixes also if(MSCV) since
  MINGW, MSVC, CYGWIN etc. are undefined until project is declared

### CODE REVIEW

**Comment by GitMensch** [comment]
Thank you for this PR. Why do you added `-static-libgcc`? I agree that it is a reasonable _option_ but if the software that links against the build also uses libgcc it is better be shared in most cases (which isn't the case when both link statically - in this case both have their own environment).

**Comment by sherpya** [comment]
> Thank you for this PR. Why do you added `-static-libgcc`? I agree that it is a reasonable _option_ but if the software that links against the build also uses libgcc it is better be shared in most cases (which isn't the case when both link statically - in this case both have their own environment).

I don't known why the project dynamically links libgcc (there is something , but rarely it's a good idea to have a dll dependency instead of few bytes added to executable, this makes sense instead for libstdc++ that makes the execuable bigger

**Comment by GitMensch** [comment]
I don't know why the C compiler decides to use [libgcc](https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html) at all here and given its documented set of functions it could be integrated, but this does not only apply to MinGW...

I suggest to pull the changes in without this change and you may add a new PR for `-static-libgcc`, which then is possibly related to GCC, not to MinGW.

Are you OK with me reverting these lines and pull the change in?

**Comment by sherpya** [comment]
> I don't know why the C compiler decides to use [libgcc](https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html) at all here and given its documented set of functions it could be integrated, but this does not only apply to MinGW...
> 
> I suggest to pull the changes in without this change and you may add a new PR for `-static-libgcc`, which then is possibly related to GCC, not to MinGW.
> 
> Are you OK with me reverting these lines and pull the change in?

I have no problems, I currently build pdcurses using custom makefile on the root of my project https://github.com/clamwin/clamav-win32,
I've used the project cmake to check some stuff and noticed the broken build on mingw

yes and -static-libgcc it's unrelated

**Comment by sherpya** [comment]
https://github.com/Bill-Gray/PDCurses/commit/7cf330d2ce4f3b70ec46b3170751b7802ec4eb75#commitcomment-39733292

**Comment by sherpya** [comment]
I've discovered dependency for libgcc, I think it's only 32bit,
in `wingui/pdcscrn.c` the function `milliseconds_since_1970`
makes a 64bit division, that is not native on 32bit so it links `_udivdi3` from `libgcc_s_sjlj-1.dll` in my case, I'll make you a pr

**Comment by GitMensch** [comment]
@sherpya Good catch!

**Pull request merged**
