### PR TITLE
new define `PDC_HAS_VERSION_INFO` providing external programs with a safe check if this is available or not

### PR DESCRIPTION
**Pull request by GitMensch**
change for https://github.com/Bill-Gray/PDCurses/issues/21
* removed `const` modifier from `PDC_version` as this is not available at compile but only at run time
* added define `PDC_HAS_VERSION_INFO` to provide external programs with a safe check if this is available or not

### CODE REVIEW

**Comment by Bill-Gray** [comment]
I can sort of see the logic of that error message.  The fact that it's showing up in your version of VS but not in mine (I'm running VS2013,  plus various other compilers) suggests that it's not a requirement of C,  just something where some compilers disagree with others (and where Microsoft disagrees with its previous versions... which VS are you running?)

I _think_ we'll be okay with PDC_version not being of type const.  I'm not totally sure of that,  though;  I've a vague memory that somewhere or other,  I got into trouble and therefore added the const.  I should be able to check it out tomorrow,  along with some of the other fixes you've made.

**Comment by GitMensch** [comment]
Sounds good. Note: I won't be able to code/built/test anything for a week from Sunday on.

**Comment by GitMensch** [comment]
Note: compiled PDCurses with VC2015 this time (2015 and newer have much better support for C99+ than its preceding versions - a lot "works now" and some parts don't even compile any more :-).

**Comment by GitMensch** [comment]
Nearly integrated with d6c808545d0a942cdeb2097413e04acd77cd35c6, the single line that is missing is https://github.com/Bill-Gray/PDCurses/pull/51/commits/42ff4f6832019da17bf535c38fc0fd9944ae9648#diff-50fbac6394f4e1f8aa0d6b41eea8753dR135 (135)

> added define `PDC_HAS_VERSION_INFO` to provide external programs with a safe check if this is available or not

Do you added another define which I've missed? If not I'll add a PR with this line :-)

**Comment by GitMensch** [comment]
OK, I've obviously already have this PR :-)

**Pull request merged**
