### PR TITLE
use curl for download (more reliable)

### PR DESCRIPTION
**Pull request by jmalak**
appveyor download utility is unreliable, curl get reliable results and files can be download directly to destination
restructure appveyor.yml little bit to separate configuration/installation/build

### CODE REVIEW

**Comment by GitMensch** [comment]
I like that, just to recheck: Appveyor says its tool is nice because it allows to set timeouts (default: 5 minutes), can you add a reasonable set of `--connect-timeout` and `--max-time` to your PR?

**Comment by jmalak** [comment]
I updated curl timeout value by explicit one.
--connection-timeout=30 seconds (used only for establish connection with peer)
--max-time=300 seconds (this time is total time for everything)
I added curl defaults in the comment if I got it.

**Comment by GitMensch** [comment]
Fixed [`--connect-timneout`](https://curl.haxx.se/docs/manpage.html#--connect-timeout),´ in 8e9625cf0ba59723d7dbbca5732907cb5bc4ded4. Doing so made me wonder why we don't cache the ow downloads. @jmalak Do they change without changing the URL? If not I'll add caching those files.

**Comment by jmalak** [comment]
I tried on travis but it is not much suitable for input artifact, it is oriented to build as cash for output artifact.
Each matrix or job entry has its own cache that use it for input artifact has no sense.
Travis doesn't support any shared cache. I don't know if appveyor use something different on entry.

**Comment by GitMensch** [comment]
The main question is: does the *content* at these exact ow-URLs change?

**Comment by jmalak** [comment]
OW 1.9 is fixed.
OW 2.0 is still beta that it changes dynamicaly.

**Comment by GitMensch** [comment]
The reliable curl raised an error with
~~~
Installing Open Watcom 1.9 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21171  100 21171    0     0  21171      0  0:00:01 --:--:--  0:00:01 39870
100 21158  100 21158    0     0  21158      0  0:00:01 --:--:--  0:00:01 21158
100 21252  100 21252    0     0  21252      0  0:00:01 --:--:--  0:00:01 21252
100   391  100   391    0     0    391      0  0:00:01  0:00:01 --:--:--  3587
 64 80.1M   64 51.6M    0     0   176k      0  0:07:45  0:05:00  0:02:45  125k
curl: (28) Operation timed out after 298844 milliseconds with 54198022 out of 84012543 bytes received
Command exited with code 28
~~~

I'll add the caching for ow on Appveyor soon.

> OW 1.9 is fixed.
> OW 2.0 is still beta that it changes dynamicaly.

The current url for ow20beta includes "open-watcom-2_0-c-win-x64.exe" - is there a versioned artifact that we may use (and obviously adjust from time to time) instead of "same URL, different content"?

**Comment by jmalak** [comment]
it is not planned to do it because we are still in beta and my resources are limited.
as soon as we do some official build it must be supported. 
We could do periodic month snapshot, because one set of full build take about 1.5 GB of disk space.

**Pull request merged**
