### PR TITLE
Correct OW cross-compile stuff to work with Travis

### PR DESCRIPTION
**Pull request by jmalak**
Travis has some asumption about compilers that safer is specify it explicitly for cross-compilation then use CMake detection. For CMake and Linux must be differ between names with and without file name extension.

### CODE REVIEW

**Comment by GitMensch** [comment]
This PR is hard to review as neither before nor after there are actually any OW entries in travis. Can you add those in this PR, too, please?

**Comment by jmalak** [comment]
Existing matrix - dimensions (os, compiler, env) is used as before.
I added OW support by extra matrix entries.
Both can be handled separately.

**Comment by jmalak** [comment]
I don't know how the report table for Travis build is done, but new architecture column should be add there.

**Comment by GitMensch** [comment]
Thank you for working on this. Please only add the watcom home variable for the builds actually using it.

**Comment by jmalak** [comment]
I corrected it and little bit restructure travis.yml file

**Comment by GitMensch** [comment]
Looks good, you may choose to either comment the ow20 builds if you don't think they'll be fixed soon and I'll merge the pull request or we keep it open until ow20 corss-compilation is fixed. @jmalak  What is your take on this?

**Comment by jmalak** [comment]
I am working on wmake fix just now. That fixed version will be available after one or two days.

**Comment by jmalak** [comment]
OpenWatcom 2.0 wmake tool is fixed now that all is build OK.

**Comment by GitMensch** [comment]
Thank you very much @jmalak.
Could you please go on and try to add the new dosvga port to ow cross compilation and, if possible, wincon+wingui+vt?

**Comment by jmalak** [comment]
Do you mean cross-compilation to Windows from Linux?

**Comment by GitMensch** [comment]
> Do you mean cross-compilation to Windows from Linux?

Yes, included in the travis build (and before: adding the dosvga port to the existing dos compilation entries, if possible; if not create a new set for it)...

**Comment by jmalak** [comment]
OK. I will extend the objects/ports as first and next prepare cross-compilation for Windows.

**Comment by jmalak** [comment]
In sub-directory dosvga is missing CMakeLists.txt file I created new one as copy from dos project.
I checked to build Wide version for 16-bit DOS and there is lot of type mismatches. It looks like it was developed only for 32-bit DOS. DO you have any idea about dosvga project targets?

**Pull request merged**
