### PR TITLE
improve responsiveness while traceon() is enabled

### PR DESCRIPTION
**Pull request by flrl**
... by not opening and closing the log file for every written line

### CODE REVIEW

**Comment by GitMensch** [comment]
Thank you for the PR. The main part "don't open+write+close for any tracing" is definitely correct. Additional this leads to one error (in trace_on) when the trace file cannot be opened instead of an error for each traced function.

But I see some issues here:

* To provide the same feature the old tracing functionally has we should flush the file after the print. This likely means a big decrease in performance again - can you provide some data for "old/suggested/suggested with flush"? If we have a big performance penalty I suggest to check a new environment variable in trace_on to disable the flush (which should still be the standard to not change the behavior).
* The log for "trace on" should still occur on the beginning, maybe another "trace on failed" when the file cannot be opened.

**Comment by Bill-Gray** [comment]
"...To provide the same feature the old tracing functionally has we should flush the file after the print."

I had the same thought;  if we flush,  the performance would be (I think) about where we started.  _However_,  that flushing is really needed only in cases where the program in question crashes or hangs (situations where we'd lose unflushed data).  So we might take this fix with a line such as
```
/* Uncomment this if your program is crashing/hanging and you're losing
some debugging info  */
/*  fflush( pdc_dbfp); */
```
   ...thus getting the improved responsiveness most of the time,  with the
option still there to get a fully flushed data file.  (And I don't know for a fact
that write/flush is,  in fact,  just as slow as open/write/close.)

**Comment by GitMensch** [comment]
> And I don't know for a fact that write/flush is, in fact, just as slow as open/write/close.

Cannot be: open allocates, close frees both including file handles.

>  So we might take this fix with a line such as...

Nope: breaks everything if you have to change and recompile. But if you say so I change my request for @flrl 

```diff
-if we have a big performance penalty I suggest to check a new environment variable in trace_on to disable the flush (which should still be the standard to not change the behavior)
+to allow both the speedup and the option to trace as it was before I suggest to check a new environment variable in trace_on to enable the old "flush always"
```

**Comment by flrl** [comment]
Thanks for the review :)

My understanding: `fflush()` flushes the userspace `FILE *` buffer contents to kernel space; `fsync()` flushes the underlying kernel space buffers.  But my understanding is based on Linux -- I'm very very new to Windows development -- so I don't know whether that holds.

Speculatively though, based on my understanding, adding `fflush()` calls alone probably won't add significant performance hit; but also won't preserve the "each logged line is definitely in the file" behaviour unless `fsync()` is called too.

I don't have any profiling tools yet, so my data at the moment is purely anecdotal (observing response to keystrokes in a simple menu similar to the one in the testcurs demo).  But I'll have a play and see what difference each of `fflush()` and `fsync()` make (for interest), and make them controllable by environment variable.

> The log for "trace on" should still occur on the beginning, maybe another "trace on failed" when the file cannot be opened.

I'm not sure what you mean by this?  If the "traceon() called" is logged before the flag/FILE is enabled, the PDC_LOG macro will eat it.  The only way you'd ever see "traceon() called" being logged is if you called it while it was already enabled (but maybe that's what we wanted to see?).  My reading was that the intent here was to have a searchable start point in the (possibly large and historical) "trace" file, in which case it needs to not log "traceon() called" until the log is actually enabled?

**Comment by Bill-Gray** [comment]
@GitMensch : "Nope: breaks everything if you have to change and recompile."

True;  at the very least,  that should be switched around to say
```
/* Comment out the following line if performance is an issue. */
 fflush( pdc_dbfp);
```
As to whether doing `fflush` will ensure the log is actually flushed to the hard drive:  it occurs to me that when I've needed to ensure that behavior,  I used `setvbuf( ofile, NULL, _IONBF, 0);` (i.e.,  don't buffer the output to the file.) That could be done here as well,  with a similar "comment out the following line..." comment.

I think that in theory,  using `setvbuf` (once,  when the file is opened) should have exactly the same effect as calling `fflush` after each write.  But that's theory.

@flrl - in re 'anecdotal' testing: seems to me that ought to be sufficient,  since what really matters here is the subjective,  user experience of "does this feel as if it's responding".  If you find that the program becomes unresponsive with tracing turned on,  and becomes responsive with it turned off,  and is also responsive with tracing turned on as long as the output is left buffered,  then you know what you need to know about the performance.

**Comment by flrl** [comment]
Okay, so: once the trace file is no longer being open/closed for each write, the difference in responsiveness between whether we `fflush()` or not doesn't seem observable (at least for a trivial program).  But it's permissable for the OS/disk cache/etc to buffer it further, so it stilll doesn't entirely guarantee the log line is stored (but neither does `fclose()`, for that matter).

`fsync()` is a POSIX function, not available on Windows (unless you're using a POSIX wrapper such as MingW, which provides an implementation of it).  I don't think this particular rabbit is worth chasing, given its platform-dependence.

I'm not sure whether the `fflush()` performance hit will be more noticeable under a heavier load than I've tested with, but I'll assume it may be, and proceed as planned: optional `fflush()` after each log line, controlled by environment variable, default off.

**Comment by flrl** [comment]
I've made it re-check the environment variable each time `traceon()` is called, rather than just once and caching the value, on the off chance someone is doing some tricky debugging of a long-running program and only wants the flushing behaviour sometimes.

**Comment by GitMensch** [comment]
Looks very nice. As @Bill-Gray already said that he liked the changes, too I'm merging it.

BTW: @flrl What are your experiences with tracing active in the new code with/without flush about the responsiveness? Are there more PR "to be expected" (where you may currently use the trace to verify everything works)?

**Comment by flrl** [comment]
In the old code (with open+close for each write), in a simple menu similar to the testcurs one, if I alternated up/down arrow keys quickly for a few seconds, then the on screen representation would continue to scroll up/down the menu for a few extra seconds while it caught up on the pending keystrokes.

In the new code (one open/close per traceon/traceoff pair), I can't make it lag like that even with fflush enabled.

I initially enabled traceon/DEBUG=Y while I was trying to figure out what my app was doing wrong -- I can't remember what now, but I've already solved it anyway.  But it was while investigating that that I noticed the sluggishness and investigated that too.  If I come across anything else I'll certainly submit PR's, but I don't have any outstanding issues with PDCurses at this stage.

**Pull request merged**
