### PR TITLE
appveyor - simple solution of OW download from Sourceforge problem

### PR DESCRIPTION
**Pull request by jmalak**
expectation that if new download request start then sourceforge redirect to different site is correct
now 3 attempts should be OK to get working connection instead of retry to same address which was done by original solution
from testing most of connection is OK for first attempt, some of series (1 or 2) do second request to be OK
I setup full timeout to only 3 minutes to get better connection when it is working very slowly
No loop, simply try next attempt if previous not succeed

### CODE REVIEW

**Comment by jmalak** [comment]
It looks like we could setup --max-time lower to not wait too long because working connection download artifact in seconds
maybe add one attempt to 4 total and shorting timeout to 1 minute or lower get best response

**Comment by jmalak** [comment]
I optimize timeout values to get better response
--keepalive-time=10
--connect-timeout=10
--max-time=60
max. number of atempts is 4
it looks fine

**Comment by jmalak** [comment]
Unfortunately you are right, I submit some old version, my solution was using
(curl ... & if errorlevel == 1 curl ... &  ...) &&
but with || it is simpler.

**Comment by jmalak** [comment]
the appveyor-repeat implementation is for standalone command can not be used in multi-command line environment and do fixed 3 attempts.
my solution is not nice but is transparent even if it is not as simple as one command

**Comment by GitMensch** [comment]
> the appveyor-repeat implementation is for standalone command can not be used in multi-command line environment and do fixed 3 attempts.

I confess I'm confused.

The current version is:

```yaml
      (curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%" ||
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%" ||
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%" ||
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%") &&
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%" &&
      set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%"
```

Isn't that the same as:

```yaml
      (appveyor-retry curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%") &&
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%" &&
      set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%"
```

... and I _guess_ the following may be preferable (break because of the failing command, if it fails):

```yaml
      appveyor-retry curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%"
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%"
      set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%"
```

**Comment by jmalak** [comment]
Because it is conditional block and in YML it is one block  that you need separate commands, it is one long line.
As standalone commands it works but as conditional block doesn't.

**Comment by jmalak** [comment]
This works as expected
```
install:
  - if "%TOOLCHAIN%"=="Watcom19" ( 
      echo Installing Open Watcom 1.9 &&
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%" &&
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%" &&
      set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%" &&
    )
```

This doesn't
```
install:
  - if "%TOOLCHAIN%"=="Watcom19" ( 
      echo Installing Open Watcom 1.9
      curl %CURL_ARGS% --output "%TEMP%\%ARTIFACT_NAME%" "%ARTIFACT_URL%"
      7z x -y "%TEMP%\%ARTIFACT_NAME%" -o"%WATCOM%"
      set "PATH=%WATCOM%\BINNT;%WATCOM%\BINW;%PATH%"
    )

```

**Comment by jmalak** [comment]
Problem with `appveyor-retry` command is resolved.
For some unknown reason `appveyor-retry` command somehow break PATH setup.
PATH setup must be done in another block of command after otherwise PATH is wrong.
It was reason why it didn't worked.

**Comment by GitMensch** [comment]
Thank you for your work, I've came up with something similar checked-in with 1a94ea162323e73b2465804573665e3973821813

**Comment by GitMensch** [comment]
... Guess what I've just got:

~~~
Installing Open Watcom 1.9 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Connection timed out after 10000 milliseconds
Command "curl --location --fail --show-error --keepalive-time 10 --connect-timeout 10 --max-time 60 --output "C:\Users\appveyor\AppData\Local\Temp\1\open-watcom-c-win32-1.9.exe" "https://sourceforge.net/projects/openwatcom/files/open-watcom-1.9/open-watcom-c-win32-1.9.exe"" failed with exit code 28. Retrying 2 of 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21171  100 21171    0     0  21171      0  0:00:01 --:--:--  0:00:01 43651
100 21158  100 21158    0     0  21158      0  0:00:01 --:--:--  0:00:01 20.1M
100 21240  100 21240    0     0  21240      0  0:00:01 --:--:--  0:00:01 21240
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
curl: (28) Connection timed out after 10281 milliseconds
Command "curl --location --fail --show-error --keepalive-time 10 --connect-timeout 10 --max-time 60 --output "C:\Users\appveyor\AppData\Local\Temp\1\open-watcom-c-win32-1.9.exe" "https://sourceforge.net/projects/openwatcom/files/open-watcom-1.9/open-watcom-c-win32-1.9.exe"" failed with exit code 28. Retrying 3 of 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (28) Connection timed out after 10000 milliseconds
Sorry, we tried running command for 3 times and all attempts were unsuccessful!
Command exited with code 28
~~~

Obviously we cannot do anything against broken external servers, but with the addition of a cache (I want to do this sometime until end of the weekend) the 1.9 version should be only downloaded once (it currently is downloaded for each build and each ow19 env).

**Comment by jmalak** [comment]
You are right, if it is broken too much then we can not do much.
It looks like 3 attempt is still low.
If some caching on appveyor is possible then it should help.

**Pull request closed without merging**
