### PR TITLE
enable DOS VT project build by Open Watcom

### PR DESCRIPTION
**Pull request by jmalak**
enable build by appveyor and travis

### CODE REVIEW

**Comment by GitMensch** [comment]
OW19 worked, OW20 failed, I guess that's an issue with OW20 not this repo or the travis setup?

**Comment by jmalak** [comment]
It is some problem for one download only, 3 attempts failed and next failed due to OW2.0 doesn't exist, submit next build for tih PR and I believe it  will be OK

**Comment by GitMensch** [comment]
I've restarted the failing job, now all works.
It would we good if we could abort the job if travis_retry returns non-zero or at least if ow20 --version fails (instead of going on to the build and get a less obvious error from cmake).

**Comment by jmalak** [comment]
I submit new PR to fix this on travis.

**Pull request merged**
