### PR TITLE
Add functions to get pointers to ends of the stack of panels

### PR DESCRIPTION
**Pull request by CraftCoderr**
I want to calсulate on which panel was mouseclicked and for this I need to get top panel to iterate through stack from top to bottom panel.

### CODE REVIEW

**Comment by Bill-Gray** [comment]
I admit that I've made exactly zero use of the panel library,  so please go easy on me if the following is wrong/stupid.
Looking at `panels.c`,  it appears that `panel_below(NULL)` returns `_top_panel`,  and `panel_above(NULL)` returns `bottom_panel`.  I don't think separate functions are required.
Dunno if `ncurses` handles things the same way.  But of course,  adding functions to PDCurses wouldn't fix `ncurses` anyway.

**Comment by GitMensch** [comment]
>  it appears that `panel_below(NULL)` returns `_top_panel`, and `panel_above(NULL)` returns `bottom_panel`. I don't think separate functions are required.

Is this covered in the user guide?

**Comment by Bill-Gray** [comment]
> Is this covered in the user guide?

I didn't even look there.   But yes,  [`MANUAL.md`](https://github.com/Bill-Gray/PDCurses/blob/master/docs/MANUAL.md) says
```
   panel_below() returns a pointer to the panel in the deck below pan,
   or NULL if pan is the bottom panel. If the value of pan passed is
   NULL, this function returns a pointer to the top panel in the deck.
```
   (and similarly for `panel_above()`).  Looking at [this man page for the panel library](https://man7.org/linux/man-pages/man3/panel.3x.html),  I see that `ncurses` does the same thing.

That man page also describes `ncurses` extensions `ground_panel()` and `ceiling_panel()`,  which map to `panel_above( NULL)` and `panel_below( NULL)`,  respectively.  Essentially,  they are the functions for which @CraftCoderr was looking.  I don't see a really strong need for them,  but if I saw `ceiling_panel(SP)`,  I'd assume right away that the uppermost panel was meant;  if I saw `panel_below(NULL)`,  I'd have to look it up.  Which may be why Thomas Dickey,  the maintainer of `ncurses`,  added them.

**Comment by GitMensch** [comment]
In that case: please reopen and add the ncurses' extensions (both for clarity and for portability).

**Comment by Bill-Gray** [comment]
Fixed and functions added (commit 63da6310fc931798666d55811649428f77d119c).
This turned into a bigger deal than I expected.  As mentioned above,  I had no real knowledge of the panel library.  We have a new `test_pan` demo (see commit 91415a3987d31) in which panels can be swapped around,  moved,  hidden,  and shown.  The PDCurses panel library had bugs causing garbage display (commits 765901f6f0d7ef and 51ccf6f1d43d45a105).  Resizing the window to make it smaller,  such that a panel ends up partially off-screen,  causes a crash (still unfixed in PDCurses;  ncurses lacked any of these bugs).
`ceiling_panel()` and `ground_panel()` are unavailable on older ncurses.  See `test_pan.c` for a way around this.

**Pull request closed without merging**
