### PR TITLE
roll sdl2/sdl2 ttf versions, remove un-used parameter

### PR DESCRIPTION
**Pull request by jwinarske**
Fix for VS2015 SDL2 x86 build

[CI Build](https://ci.appveyor.com/project/jwinarske/pdcurses-21dj3)

### CODE REVIEW

**Comment by GitMensch** [comment]
Thank you. As I've just recognized this - do you see a reason that the Travis build does not include sdl(1) / x11?

**Comment by Bill-Gray** [comment]
And/or DOSVGA.  I'd be happy to see Travis working on all platforms,  provided it works in a passably stable manner.  But we might want to focus on getting what we've got working,  then going to 4.2.0,  then leaving further Travis expansion for 4.2.1.
I'm fine either way,  but gather there is considerable desire to get 4.2.0 released without too much delay.
Great to see the progress on this!

**Comment by jwinarske** [comment]
CMake support for SDL1 would have to be built from scratch, unless someone has done that in the last two years.  That doesn't excite me.  I think we have pretty comprehensive compiler coverage - Windows, GCC, Clang, and Watcom.  I think moving forward it would be wise to add VS2019 and at least Clang 10.0.0.  Perhaps deprecate VS2015.  With Clang 10.0.0 introduce a static analysis matrix.  That said I would be more interested in implementing a Wayland curses...

**Comment by GitMensch** [comment]
@jwinarske let's leave SDL1 behind then.

As the CI builds are all finished now and green I'll merge this one.

**Pull request merged**
