### PR TITLE
add dosvga project to travis build for 16 and 32-bit DOS

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by jmalak** [comment]
I added only single-byte-encoding character versions build for 16/32-bit DOS.
WIDE version build fails for some type truncations and type mismatches.
Need review and fixing.

**Comment by GitMensch** [comment]
Thanks, I've reported the wide issue, we'll see where this can be added. This PR is merged.

As you obviously tried using the broken wide stuff: can you please provide another PR with those changes in (and an expected failed check)? This way we can leave it open and trigger the check later again when the dosvga port is updated.

Again: thank you very much for your work. If you find some time the addition of cross-compiling to win32 (and if available in ow to win64) of wingui+wincon+vt would be nice; ideally using only one build environment for all together (like done for clang for example with sdl2, x11 and vt).

**Comment by GitMensch** [comment]
Hm, is it too much to ask to add the dosvga port, now that the missing CMake parts are in, also to appveyor.yml? Background: This environment provides the actual binaries as downloadable artifacts.

**Comment by Bill-Gray** [comment]
Wide-char builds were broken with 64-bit `chtype`s if you built for 16-bit DOS.  Commit eb8ed317 fixes this.
Existing psf2 fonts generally don't include many characters.  For testing,  I've [converted GNU Unifont to psf2](https://www.projectpluto.com/temp/unifont.psf).  I'll post the code used to do this in a bit.  Only halfwidth characters are converted;  something odd will have to be done to support Asian languages and emoji,  and I haven't tackled combining characters yet.  SMP characters (those with Unicode points past 64K) _should_ be supported,  but don't work,  even on 32-bit builds.

**Comment by jmalak** [comment]
In the past I was using Travis for OW build/test and tested appveyor little bit for Windows platform.
But I must abandon it and move all to Azure pipeline.
Main reason was that resources on Travis were very limited -  maximum run-time for one job was too low than our jobs need and also log files are limited by size that we have problem with useless logs which can hold only minimal info. 
Now we are on Azure Pipeline and there is no such limitation that we can get all details for build if we need to analyse it. Also Azure Pipeline has all platforms available with good support.
Azure Pipeline also support artifacts (we use it internaly during build/test stages) but final binary we move as release to Github (Azure pipeline support Github releases). Thanks Azure Pipeline we have one configuration for all and our live is much easier then with Travis. But it is due to size of OW project. For your project Travis is OK, but if you want artifacts maybe you could use Github releases with Travis and abandon appveyor. If we used Travis we used stages/jobs for workflow and we used cache to temporarily save artifacts and after successful build/test we upload it to github.

**Comment by GitMensch** [comment]
Ok, so the issue was only related to this repo. @jmalak I'm away for some days but either you or @Bill-Gray may want to enable the wide version in Travis, too.

I'm open to adjust the CI/CD process, but would like to prevent that this is done only with one "provider". So, @jmalak if you find the time to add more cross-compilation via ow to travis and possibly add some of the missing cross-compilation parts to appveyor I'd still would be happy for this. After the 4.2 release we can check what to do about CI/CD in general.

**Comment by jmalak** [comment]
I understand you, It is only my idea how could be CI/CD integration improved.

**Pull request merged**
