### PR TITLE
travis - simple solution of OW download from Sourceforge problem

### PR DESCRIPTION
**Pull request by jmalak**
expectation that if new download request start then sourceforge redirect to different site is correct
now 4 attempts should be OK to get working connection instead of retry to same address which was done by original solution
from testing most of connection is OK for first attempt, some of series (1 or 2) do second request to be OK
I setup full timeout to only 1 minute to get better connection when it is working very slowly
No loop, simply try next attempt if previous not succeed

### CODE REVIEW

**Comment by GitMensch** [comment]
Thank you for working on this. The additional changes highlight that we have the same stuff in there multiple times. Can we define a shell function curl_retry() for the download part and use this in travis? In the theoretical case of a broken 4th download we should echo an error to stdout and exit, can you add this please?

**Comment by jmalak** [comment]
I will create subdirectory CI and put it there. Are you OK with it?

**Comment by jmalak** [comment]
I did some testing and it looks like travis download 
travis_retry wget  is enough reliable (use similar algorithm as I with curl) that is not necessary to introduce this change. It is only necessary on appveyor.

**Comment by GitMensch** [comment]
> I will create subdirectory CI and put it there. Are you OK with it?

I meant to define a function within the yml file, not a different script. This does work on appveyor (I use this for GnuCOBOL).

>  did some testing and it looks like travis download
travis_retry wget is enough reliable (use similar algorithm as I with curl) that is not necessary to introduce this change. It is only necessary on appveyor.

OK. Then maybe the change for #142 would be to use [`appveyor-retry`](https://help.appveyor.com/discussions/problems/22265-start-filedownload-retry-mechanism)?

**Comment by GitMensch** [comment]
Hm, thinking again - maybe we still should use curl with the timeout parameters instead of wget? In any case it seems reasonable to use the same procedure for both travis and appveyor.

**Comment by jmalak** [comment]
On travis is problem that each command has its own context.
I don't do any function inlining there, probably impossible.
I can create temporary shell script and next run it as command to return value to be handled by travis.
But travis-retry looks OK only problem with appveyor.
I will try appveyor-retry it could solve a problem consistently with travis.

**Comment by GitMensch** [comment]
This leaves only one open point here:
You've previously found (for appveyor) that `curl` is preferable to `wget` - so shouldn't travis be adjusted (at least for doing the consistent same thing as appveyor does)?

**Comment by jmalak** [comment]
I think that travis and appveyor and windows command processor and bash shell is very different environment that difference in appropriate YML will be alway significant.
By example travis support anchors/aliases but appveyor doesn't etc.
also default installed utility set is different by exaple travis has both curl and wget but appveyor has only curl etc. if you want to use same tool then you can but it means that you will need to install it on one system if it is not available on both systems
also matrix dimensions are different etc. each of this systems are its own world

**Pull request closed without merging**
