### PR TITLE
Reorganize .travis.yml file and add DOSVGA wide version build

### PR DESCRIPTION
**Pull request by jmalak**
reorganize file to be more readable
use travis matrix dimensions environment variables to define all dependent variables to simplify travis jobs definition
setup TRAVIS_ARCH environment variable because Travis doesn't handle it correctly (new feature, not fully implemented)
use YML anchors and aliases to do file more readable
add DOSVGA wide version build

### CODE REVIEW

**Comment by GitMensch** [comment]
Travis [shows an error](https://travis-ci.com/github/Bill-Gray/PDCurses/jobs/342582402) ow19, cross compile to dos.

**Comment by jmalak** [comment]
The problem is caused by download OW 1.9 from sourceforge it fails, but not detected by travis that continue and failed during compiler detection (compiler is not installed), could be problem with travis repeat and wget.
I will try to change travis script to identify such error properly and don't confuse users by incorrect information about source of problem.

**Comment by GitMensch** [comment]
Do you want to add this in this PR or create another one?

**Comment by jmalak** [comment]
I will create new one to loop over download.
It looks like sourceforge has problem with some sites. I don't know logic to do load balancing by sourceforge. I will try to do always new download with small delay to get chance sourceforge get new site which works correctly. Anyway it is strange sourceforge do about 3 redirection to get final download site.

**Pull request merged**
