### PR TITLE
Added automatic font-scaling for "DPI-aware" applications.

### PR DESCRIPTION
**Pull request by clangen**
I recently replaced my old laptop with a new one that has a high-DPI display. When I loaded up my win32a/PDCurses app the font was so small I couldn't read it. After a bit of research, I discovered that I needed to do a couple things to fix this automatically for my users:

1. Mark my process as "DPI Aware". There are a couple ways to do this, either using application manifests or the newish `SetProcessDpiAwareness` Win32 API call.

2. After declaring the process as "DPI Aware", use the Win32 API call `GetDpiForSystem` to retrieve the current system DPI, and use that to normalize the default font size.

This is a patch for (2), so the default font-size is automatically scaled for applications that opt-in to this "DPI Awareness". If users do not opt-in to this behavior, no changes should be observed. Note that manual intervention is only required for the initial case, where a default font size is selected. Afterwards, the system's `ChooseFont` dialog will automatically scale selected font sizes based on the system DPI.

### CODE REVIEW

**Comment by Bill-Gray** [comment]
Thank you.  I've not encountered this issue (maybe I need to get a high-DPI display...),  but can see where it would be a problem.  I'll give your patch a try on a few machines here and see what happens.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd145037(v=vs.85).aspx

suggests two things that might help us out here.  First,  it says that if you set lfHeight=0,  "...the font mapper uses a default height value when it searches for a match."  In hindsight, I perhaps should have had PDC_font_size initialized to zero (not 12),  with some extra code to determine what that default height was determined to be when the font was first set up.

The second thing it suggests is that  "you can use the following formula to specify a height for a font with a specified point size" (and it then gives something resembling your MulDiv () code to do the scaling.)

Both fixes have the advantage of not requiring Win10 features.  I think they'd work back to Win95,  maybe even Win3.1.

I am indebted to you for showing me two things here that ought to be useful to me elsewhere,  in PDCurses and in other projects.  First,  I wasn't aware of MulDiv.  I've had plenty of situations where I needed to multiply two 32-bit quantities,  creating a 64-bit one,  and then divide by a 32-bit quantity.   I usually do this with a lot of casts.  MulDiv should be cleaner,  and should result in faster code on 32-bit machines.  (Not many of those left,  and I realize that the speed is not an issue at all in this particular case.)

On non-Windows machines,  I'd just have to write an inline MulDiv and hope the compiler was bright enough to recognize that the full force of 64-bit multiplies and divides was unnecessary (I _have_ had situations in past years where I was doing enough of these that speed became an issue.)

Second,  the method you use for determining if the GetDpiForSystem() is available is what I really _ought_ to be using to determine if GetFontUnicodeRanges() is available.  As you may have seen,  this code to determine which glyphs are available to us is determined by USE_FALLBACK_FONT;  we decide on it at compile time,  which is somewhat stupid;  what really matter is whether that function is available at runtime.  I have other,  non-PDCurses code where I've been similarly stupid.  So a general-purpose ability to say (for example)

if ((pointer_to_func = GetDLLFunc( "user32.dll", "GetDpiForSystem") != NULL) {
    (use that function)
} else {
   (use some fallback procedure to get around absence of that function)
}

   would be quite useful.  Always a good day when you learn a couple of new tricks...

**Comment by timofonic** [comment]
@Bill-Gray Any news about this?

**Comment by xobs** [comment]
I've opened pull #83 that builds on this by also registering HiDPI support request before the first window is opened.

I'm testing it with the `cursive` library in Rust, via `pancurses` via `pdcurses-sys`.

**Comment by GitMensch** [comment]
Closed in favor of #83 as the screen found there shows that #45 alone creates very small font-sized by default.
@clangen Do you have any comments to #83?

**Pull request closed without merging**
